### ISSUE TITLE
Unable to confirm subscription

### ISSUE THREAD

**Issue by astrostl** [sp52005/AWS-SNS-To-Slack-hook#1]
Howdy, found your function via a GitHub search.

I've set it up with a Slack webhook, applied IAM policy, etc. When I add it to the SNS subscription for a given topic, it reports that it is sending a confirmation message over to it. I never receive it.

But, if I manually go through SNS to 'Publish to topic', those messages ARE received, so I'm otherwise confident that everything is working - the Lambda function is getting the message across to Slack.

Any ideas on the confirmation side? Thanks!

**Comment by starrlingo** [comment]
Hi,
  Your should select SNS Subscription protocol as [AWS Lambda] and choose [sns-slack.js] Lambda.
Please update your slack url in [sns-slack.js] code in advance.

**Comment by astrostl** [comment]
Been a while since I looked at this. Thx!
